import { NextApiRequest, NextApiResponse } from "next";
import { NextResponse } from "next/server";

export const GET = async () => {
  const shirts = [
    // Shirts
    {
      id: 25,
      tags: "Shirts",
      name: "Varsity Jacket Black-White",
      fit: "Oversized",
      price: "550.000",
      image: "/boinshop/Shirts1.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "10",
      rating5: "2",
      rating4: "0",
      rating3: "2",
      rating2: "2",
      rating1: "4",
    },
    {
      id: 26,
      tags: "Shirts",
      name: "Vancarhell Jacket",
      fit: "Oversized",
      price: "530.000",
      image: "/boinshop/Shirts2.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "310",
      rating5: "50",
      rating4: "100",
      rating3: "80",
      rating2: "70",
      rating1: "10",
    },
    {
      id: 27,
      tags: "Shirts",
      name: "Jacket đen trơn hình chữ F",
      fit: "Oversized",
      price: "532.000",
      image: "/boinshop/Shirts3.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "400",
      rating5: "50",
      rating4: "100",
      rating3: "100",
      rating2: "100",
      rating1: "50",
    },
    {
      id: 28,
      tags: "Shirts",
      name: "Rabbit Hoodie Beige",
      fit: "Oversized",
      price: "450.000",
      image: "/boinshop/Shirts4.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "50",
      rating5: "10",
      rating4: "20",
      rating3: "10",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 29,
      tags: "Shirts",
      name: "Rabbit Hoodie Black",
      fit: "Oversized",
      price: "470.000",
      image: "/boinshop/Shirts5.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "60",
      rating5: "20",
      rating4: "10",
      rating3: "12",
      rating2: "10",
      rating1: "10",
    },
    {
      id: 30,
      tags: "Shirts",
      name: "Hoodie trơn đen trắng",
      fit: "Oversized",
      price: "470.000",
      image: "/boinshop/Shirts6.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "150",
      rating5: "20",
      rating4: "50",
      rating3: "20",
      rating2: "40",
      rating1: "20",
    },
    {
      id: 31,
      tags: "Shirts",
      name: "Hoodie GetUp Early Xanh",
      fit: "Oversized",
      price: "350.000",
      image: "/boinshop/Shirts7.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "40",
      rating5: "10",
      rating4: "20",
      rating3: "0",
      rating2: "0",
      rating1: "10",
    },
    {
      id: 32,
      tags: "Shirts",
      name: "Hoodie trơn xanh lá",
      fit: "Oversized",
      price: "350.000",
      image: "/boinshop/Shirts8.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "220",
      rating5: "220",
      rating4: "0",
      rating3: "0",
      rating2: "0",
      rating1: "0",
    },
    {
      id: 33,
      tags: "Shirts",
      name: "Hoodie trà sữa màu đen",
      fit: "Oversized",
      price: "500.000",
      image: "/boinshop/Shirts9.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "440",
      rating5: "400",
      rating4: "10",
      rating3: "10",
      rating2: "10",
      rating1: "10",
    },
    {
      id: 34,
      tags: "Shirts",
      name: "Hoodie trà sữa màu hồng",
      fit: "Oversized",
      price: "500.000",
      image: "/boinshop/Shirts10.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "390",
      rating5: "370",
      rating4: "5",
      rating3: "5",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 35,
      tags: "Shirts",
      name: "Hoodie trà sữa màu Beige",
      fit: "Oversized",
      price: "500.000",
      image: "/boinshop/Shirts11.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "420",
      rating5: "220",
      rating4: "20",
      rating3: "60",
      rating2: "50",
      rating1: "70",
    },
    {
      id: 36,
      tags: "Shirts",
      name: "Hoodie CREW mặt cười xanh dương",
      fit: "Oversized",
      price: "612.000",
      image: "/boinshop/Shirts12.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "420",
      rating5: "220",
      rating4: "20",
      rating3: "60",
      rating2: "50",
      rating1: "70",
    },
  ];

  return NextResponse.json(shirts);
};
