import { NextApiRequest, NextApiResponse } from "next";
import { NextResponse } from "next/server";

export const GET = async () => {
  const tshirts = [
    {
      id: 1,
      tags: "Tshirts",
      name: "Áo thun ovs from unisex cho cả nam và nữ",
      fit: "Oversized",
      price: "250.000",
      image: "/boinshop/Aothun1.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "50",
      rating5: "30",
      rating4: "5",
      rating3: "5",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 2,
      tags: "Tshirts",
      name: "Áo thun ovs from unisex cho cả nam và nữ",
      fit: "Oversized",
      price: "250.000",
      image: "/boinshop/Aothun2.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "60",
      rating5: "40",
      rating4: "5",
      rating3: "5",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 3,
      tags: "Tshirts",
      name: "Áo thun ovs from unisex cho cả nam và nữ",
      fit: "Oversized",
      price: "200.000",
      image: "/boinshop/Aothun3.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "70",
      rating5: "30",
      rating4: "20",
      rating3: "10",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 4,
      tags: "Tshirts",
      name: "Áo thun hình con gấu OVS Nam Nữ",
      fit: "Oversized",
      price: "200.000",
      image: "/boinshop/Aothun4.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "100",
      rating5: "30",
      rating4: "20",
      rating3: "20",
      rating2: "20 ",
      rating1: "10",
    },
    {
      id: 5,
      tags: "Tshirts",
      name: "Áo thun trơn đen OVS cho Nam Nữ",
      fit: "Oversized",
      price: "150.000",
      image: "/boinshop/Aothun5.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "120",
      rating5: "40",
      rating4: "20",
      rating3: "40",
      rating2: "10",
      rating1: "10",
    },
    {
      id: 6,
      tags: "Tshirts",
      name: "Áo thun hình chữ S và trơn OVS",
      fit: "Oversized",
      price: "150.000",
      image: "/boinshop/Aothun6.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "210",
      rating5: "50",
      rating4: "60",
      rating3: "50",
      rating2: "40",
      rating1: "10",
    },
    {
      id: 7,
      tags: "Tshirts",
      name: "Áo thun trơn mặt sau OVS",
      fit: "Oversized",
      price: "180.000",
      image: "/boinshop/Aothun7.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "105",
      rating5: "30 ",
      rating4: "55",
      rating3: "15",
      rating2: "5",
      rating1: "0",
    },
    {
      id: 8,
      tags: "Tshirts",
      name: "Áo thun trơn mặt sau OVS",
      fit: "Oversized",
      price: "180.000",
      image: "/boinshop/Aothun8.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "140",
      rating5: "90",
      rating4: "10",
      rating3: "10",
      rating2: "10",
      rating1: "20",
    },
    {
      id: 9,
      tags: "Tshirts",
      name: "Áo thun OVS mặt sau hình gấu ",
      fit: "Oversized",
      price: "450.000",
      image: "/boinshop/Aothun9.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "30",
      rating5: "10",
      rating4: "5",
      rating3: "5",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 10,
      tags: "Tshirts",
      name: "Áo thun trơn UNISEX",
      fit: "Oversized",
      price: "390.000",
      image: "/boinshop/Aothun10.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "55",
      rating5: "25",
      rating4: "15",
      rating3: "5",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 11,
      tags: "Tshirts",
      name: "Nolife Tshirt xanh dương",
      fit: "Oversized",
      price: "330.000",
      image: "/boinshop/Aothun11.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "83",
      rating5: "53",
      rating4: "10",
      rating3: "10",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 12,
      tags: "Tshirts",
      name: "Nolife Tshirt màu đen",
      fit: "Oversized",
      price: "330.000",
      image: "/boinshop/Aothun12.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "98",
      rating5: "58",
      rating4: "10",
      rating3: "10",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 13,
      tags: "Tshirts",
      name: "Combo áo Nolife Tshirt",
      fit: "Oversized",
      price: "600.000",
      image: "/boinshop/Aothun13.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "98",
      rating5: "5",
      rating4: "15",
      rating3: "20",
      rating2: "20",
      rating1: "38",
    },
    {
      id: 14,
      tags: "Tshirts",
      name: "Tshirt Nolife đỏ",
      fit: "Oversized",
      price: "330.000",
      image: "/boinshop/Aothun14.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "82",
      rating5: "42",
      rating4: "32",
      rating3: "4",
      rating2: "2",
      rating1: "2",
    },
    {
      id: 15,
      tags: "Tshirts",
      name: "Áo thun hình xe buýt OVS",
      fit: "Oversized",
      price: "350.000",
      image: "/boinshop/Aothun15.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "56",
      rating5: "36",
      rating4: "5",
      rating3: "5",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 16,
      tags: "Tshirts",
      name: "Áo thun RACING OVS",
      fit: "Oversized",
      price: "380.000",
      image: "/boinshop/Aothun16.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "55",
      rating5: "10",
      rating4: "35",
      rating3: "5",
      rating2: "5",
      rating1: "0",
    },
    {
      id: 17,
      tags: "Tshirts",
      name: "Áo thun hình graphic mặt quỷ",
      fit: "Oversized",
      price: "390.000",
      image: "/boinshop/Aothun17.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "85",
      rating5: "20",
      rating4: "30",
      rating3: "15",
      rating2: "10",
      rating1: "10",
    },
    {
      id: 18,
      tags: "Tshirts",
      name: "Áo thun mặt sau in hình OVS màu đen",
      fit: "Oversized",
      price: "390.999",
      image: "/boinshop/Aothun18.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "140",
      rating5: "30",
      rating4: "50",
      rating3: "40",
      rating2: "20",
      rating1: "0",
    },
    {
      id: 19,
      tags: "Tshirts",
      name: "Áo thun mặt sau in hình OVS màu trắng",
      fit: "Oversized",
      price: "399.000",
      image: "/boinshop/Aothun19.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "170",
      rating5: "30",
      rating4: "50",
      rating3: "50",
      rating2: "30",
      rating1: "10",
    },
    {
      id: 20,
      tags: "Tshirts",
      name: "Áo thun in hình chúa OVS",
      fit: "Oversized",
      price: "399.000",
      image: "/boinshop/Aothun20.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "30",
      rating5: "30",
      rating4: "0",
      rating3: "0",
      rating2: "0",
      rating1: "0",
    },
    {
      id: 21,
      tags: "Tshirts",
      name: "Áo thun in slogan mặt sau",
      fit: "Oversized",
      price: "366.000",
      image: "/boinshop/Aothun21.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "82",
      rating5: "72",
      rating4: "5",
      rating3: "5",
      rating2: "0",
      rating1: "0",
    },
    {
      id: 22,
      tags: "Tshirts",
      name: "Áo thun in hình chúa OVS",
      fit: "Oversized",
      price: "399.000",
      image: "/boinshop/Aothun22.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "67",
      rating5: "37",
      rating4: "10",
      rating3: "10",
      rating2: "0",
      rating1: "10",
    },
    {
      id: 23,
      tags: "Tshirts",
      name: "Áo thun in SLOGAN mặt trước",
      fit: "Oversized",
      price: "250.000",
      image: "/boinshop/Aothun23.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "141",
      rating5: "20",
      rating4: "50",
      rating3: "51",
      rating2: "10",
      rating1: "10",
    },
    {
      id: 24,
      tags: "Tshirts",
      name: "Áo thun chữ 7 sắc mặt sau",
      fit: "Oversized",
      price: "250.000",
      image: "/boinshop/Aothun24.jpg",
      materials:
        "Áo mang thương hiệu BoinShop được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "10",
      rating5: "2",
      rating4: "0",
      rating3: "2",
      rating2: "2",
      rating1: "4",
    },
  ];

  return NextResponse.json(tshirts);
};
