import { NextApiRequest, NextApiResponse } from "next";
import { NextResponse } from "next/server";

export const GET = async () => {
  const allCollections = [
    {
      id: 1,
      tags: "Tshirts",
      name: "Jersey T-Shirt Smaker",
      fit: "Oversized",
      price: "550.000",
      image: "/images/Ao-Smaker2.jpg",
    },
    {
      id: 2,
      tags: "Tshirts",
      name: "Cracked T-Shirt Smaker",
      fit: "Oversized",
      price: "550.000",
      image: "/images/Ao-Smaker3.jpg",
    },
    {
      id: 3,
      tags: "Tshirts",
      name: "MakeMoney Tshirt",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Ao-Smaker4.jpg",
    },
    {
      id: 4,
      tags: "Tshirts",
      name: "Jersey T-Shirt Smaker",
      fit: "Oversized",
      price: "550.000",
      image: "/images/Ao-Smaker5.jpg",
    },
    {
      id: 5,
      tags: "Tshirts",
      name: "Cracked T-Shirt Smaker",
      fit: "Oversized",
      price: "550.000",
      image: "/images/Ao-Smaker6.jpg",
    },
    {
      id: 6,
      tags: "Tshirts",
      name: "MakeMoney Tshirt",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Ao-Smaker7.jpg",
    },
    {
      id: 7,
      tags: "Tshirts",
      name: "Jersey T-Shirt Smaker",
      fit: "Oversized",
      price: "550.000",
      image: "/images/Ao-Smaker8.jpg",
    },
    {
      id: 8,
      tags: "Tshirts",
      name: "Cracked T-Shirt Smaker",
      fit: "Oversized",
      price: "550.000",
      image: "/images/Ao-Smaker9.jpg",
    },
    {
      id: 9,
      tags: "Tshirts",
      name: "MakeMoney Tshirt",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Ao-Smaker10.jpg",
    },
    {
      id: 10,
      tags: "Tshirts",
      name: "Jersey T-Shirt Smaker",
      fit: "Oversized",
      price: "550.000",
      image: "/images/Ao-Smaker11.jpg",
    },
    {
      id: 11,
      tags: "Tshirts",
      name: "Cracked T-Shirt Smaker",
      fit: "Oversized",
      price: "550.000",
      image: "/images/Ao-Smaker12.jpg",
    },
    {
      id: 12,
      tags: "Tshirts",
      name: "MakeMoney Tshirt",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Ao-Smaker13.jpg",
    },
    {
      id: 13,
      tags: "Tshirts",
      name: "Jersey T-Shirt Smaker",
      fit: "Oversized",
      price: "550.000",
      image: "/images/Ao-Smaker14.jpg",
    },
    {
      id: 14,
      tags: "Tshirts",
      name: "Cracked T-Shirt Smaker",
      fit: "Oversized",
      price: "550.000",
      image: "/images/Ao-Smaker15.jpg",
    },
    {
      id: 15,
      tags: "Tshirts",
      name: "MakeMoney Tshirt",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Ao-Smaker16.jpg",
    },
    {
      id: 16,
      tags: "Tshirts",
      name: "Jersey T-Shirt Smaker",
      fit: "Oversized",
      price: "550.000",
      image: "/images/Ao-Smaker17.jpg",
    },
    {
      id: 17,
      tags: "Tshirts",
      name: "Cracked T-Shirt Smaker",
      fit: "Oversized",
      price: "550.000",
      image: "/images/Ao-Smaker18.jpg",
    },
    {
      id: 18,
      tags: "Tshirts",
      name: "MakeMoney Tshirt",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Ao-Smaker19.jpg",
    },
    {
      id: 19,
      tags: "Tshirts",
      name: "Jersey T-Shirt Smaker",
      fit: "Oversized",
      price: "550.000",
      image: "/images/Ao-Smaker20.jpg",
    },
    {
      id: 20,
      tags: "Tshirts",
      name: "Cracked T-Shirt Smaker",
      fit: "Oversized",
      price: "550.000",
      image: "/images/Ao-Smaker21.jpg",
    },
    {
      id: 21,
      tags: "Tshirts",
      name: "MakeMoney Tshirt",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Ao-Smaker22.jpg",
    },
    {
      id: 22,
      tags: "Tshirts",
      name: "Jersey T-Shirt Smaker",
      fit: "Oversized",
      price: "550.000",
      image: "/images/Ao-Smaker23.jpg",
    },
    {
      id: 23,
      tags: "Tshirts",
      name: "Cracked T-Shirt Smaker",
      fit: "Oversized",
      price: "550.000",
      image: "/images/Ao-Smaker24.jpg",
    },
    {
      id: 24,
      tags: "Tshirts",
      name: "MakeMoney Tshirt",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Ao-Smaker25.jpg",
    },

    // Shirts
    {
      id: 25,
      tags: "Shirts",
      name: "MakeMoney Shirts",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Shirts-Smaker.jpg",
    },
    {
      id: 26,
      tags: "Shirts",
      name: "MakeMoney Shirts",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Shirts-Smaker2.jpg",
    },
    {
      id: 27,
      tags: "Shirts",
      name: "MakeMoney Shirts",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Shirts-Smaker3.jpg",
    },
    {
      id: 28,
      tags: "Shirts",
      name: "MakeMoney Shirts",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Shirt-Smaker4.jpg",
    },
    {
      id: 29,
      tags: "Shirts",
      name: "MakeMoney Shirts",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Shirts-Smaker5.jpg",
    },
    {
      id: 30,
      tags: "Shirts",
      name: "MakeMoney Shirts",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Shirts-Smaker6.jpg",
    },
    {
      id: 31,
      tags: "Shirts",
      name: "MakeMoney Shirts",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Shirts-Smaker7.jpg",
    },
    {
      id: 32,
      tags: "Shirts",
      name: "MakeMoney Shirts",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Shirts-Smaker8.jpg",
    },
    {
      id: 33,
      tags: "Shirts",
      name: "MakeMoney Shirts",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Shirts-Smaker9.jpg",
    },
    {
      id: 34,
      tags: "Shirts",
      name: "MakeMoney Shirts",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Shirts-Smaker10.jpg",
    },
    {
      id: 35,
      tags: "Shirts",
      name: "MakeMoney Shirts",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Shirts-Smaker11.jpg",
    },
    {
      id: 36,
      tags: "Shirts",
      name: "MakeMoney Shirts",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Shirts-Smaker12.jpg",
    },

    // PANTS
    {
      id: 37,
      tags: "Pants",
      name: "MakeMoney Pants",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Pants-Smaker.jpg",
    },
    {
      id: 38,
      tags: "Pants",
      name: "MakeMoney Pants",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Pants-Smaker2.jpg",
    },
    {
      id: 39,
      tags: "Pants",
      name: "MakeMoney Pants",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Pants-Smaker3.jpg",
    },
    {
      id: 40,
      tags: "Pants",
      name: "MakeMoney Pants",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Pants-Smake4.jpg",
    },
    {
      id: 41,
      tags: "Pants",
      name: "MakeMoney Pants",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Pants-Smaker5.jpg",
    },
    {
      id: 42,
      tags: "Pants",
      name: "MakeMoney Pants",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Pants-Smaker6.jpg",
    },
    {
      id: 43,
      tags: "Pants",
      name: "MakeMoney Pants",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Pants-Smaker7.jpg",
    },
    {
      id: 44,
      tags: "Pants",
      name: "MakeMoney Pants",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Pants-Smaker8.jpg",
    },
    {
      id: 45,
      tags: "Pants",
      name: "MakeMoney Pants",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Pants-Smaker10.jpg",
    },
    {
      id: 46,
      tags: "Pants",
      name: "MakeMoney Pants",
      fit: "Oversized",
      price: "500.000",
      image: "/images/Pants-Smaker11.jpg",
    },
  ];

  return NextResponse.json(allCollections);
};
