import { NextApiRequest, NextApiResponse } from "next";
import { NextResponse } from "next/server";

export const GET = async () => {
  const allCollections = [
    {
      id: 1,
      tags: "Tshirts",
      name: "Jersey T-Shirt Smaker",
      fit: "Oversized",
      price: "550.000",
      image: "/images/Ao-Smaker2.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "50",
      rating5: "30",
      rating4: "5",
      rating3: "5",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 2,
      tags: "Tshirts",
      name: "Cracked T-Shirt Smaker",
      fit: "Oversized",
      price: "540.000",
      image: "/images/Ao-Smaker3.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "60",
      rating5: "40",
      rating4: "5",
      rating3: "5",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 3,
      tags: "Tshirts",
      name: "MakeMoney Love Tshirt",
      fit: "Oversized",
      price: "530.000",
      image: "/images/Ao-Smaker4.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "70",
      rating5: "30",
      rating4: "20",
      rating3: "10",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 4,
      tags: "Tshirts",
      name: "Blacket T-Shirt Smaker",
      fit: "Oversized",
      price: "520.000",
      image: "/images/Ao-Smaker5.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "100",
      rating5: "30",
      rating4: "20",
      rating3: "20",
      rating2: "20 ",
      rating1: "10",
    },
    {
      id: 5,
      tags: "Tshirts",
      name: "Velvet T-Shirt Smaker",
      fit: "Oversized",
      price: "600.000",
      image: "/images/Ao-Smaker6.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "120",
      rating5: "40",
      rating4: "20",
      rating3: "40",
      rating2: "10",
      rating1: "10",
    },
    {
      id: 6,
      tags: "Tshirts",
      name: "Plished Tshirt",
      fit: "Oversized",
      price: "350.000",
      image: "/images/Ao-Smaker7.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "210",
      rating5: "50",
      rating4: "60",
      rating3: "50",
      rating2: "40",
      rating1: "10",
    },
    {
      id: 7,
      tags: "Tshirts",
      name: "Plouze T-Shirt Smaker",
      fit: "Oversized",
      price: "380.000",
      image: "/images/Ao-Smaker8.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "105",
      rating5: "30 ",
      rating4: "55",
      rating3: "15",
      rating2: "5",
      rating1: "0",
    },
    {
      id: 8,
      tags: "Tshirts",
      name: "Brism T-Shirt Smaker",
      fit: "Oversized",
      price: "450.000",
      image: "/images/Ao-Smaker9.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "140",
      rating5: "90",
      rating4: "10",
      rating3: "10",
      rating2: "10",
      rating1: "20",
    },
    {
      id: 9,
      tags: "Tshirts",
      name: "Fished Tshirt",
      fit: "Oversized",
      price: "450.000",
      image: "/images/Ao-Smaker10.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "30",
      rating5: "10",
      rating4: "5",
      rating3: "5",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 10,
      tags: "Tshirts",
      name: "Felure T-Shirt Smaker",
      fit: "Oversized",
      price: "390.000",
      image: "/images/Ao-Smaker11.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "55",
      rating5: "25",
      rating4: "15",
      rating3: "5",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 11,
      tags: "Tshirts",
      name: "Gouzish T-Shirt Smaker",
      fit: "Oversized",
      price: "440.000",
      image: "/images/Ao-Smaker12.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "83",
      rating5: "53",
      rating4: "10",
      rating3: "10",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 12,
      tags: "Tshirts",
      name: "Dishma Tshirt",
      fit: "Oversized",
      price: "560.000",
      image: "/images/Ao-Smaker13.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "98",
      rating5: "58",
      rating4: "10",
      rating3: "10",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 13,
      tags: "Tshirts",
      name: "Nourage T-Shirt Smaker",
      fit: "Oversized",
      price: "570.000",
      image: "/images/Ao-Smaker14.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "98",
      rating5: "5",
      rating4: "15",
      rating3: "20",
      rating2: "20",
      rating1: "38",
    },
    {
      id: 14,
      tags: "Tshirts",
      name: "Slinked T-Shirt Smaker",
      fit: "Oversized",
      price: "580.000",
      image: "/images/Ao-Smaker15.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "82",
      rating5: "42",
      rating4: "32",
      rating3: "4",
      rating2: "2",
      rating1: "2",
    },
    {
      id: 15,
      tags: "Tshirts",
      name: "Organize Tshirt",
      fit: "Oversized",
      price: "660.000",
      image: "/images/Ao-Smaker16.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "56",
      rating5: "36",
      rating4: "5",
      rating3: "5",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 16,
      tags: "Tshirts",
      name: "Erisma T-Shirt Smaker",
      fit: "Oversized",
      price: "690.000",
      image: "/images/Ao-Smaker17.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "55",
      rating5: "10",
      rating4: "35",
      rating3: "5",
      rating2: "5",
      rating1: "0",
    },
    {
      id: 17,
      tags: "Tshirts",
      name: "Quinty T-Shirt Smaker",
      fit: "Oversized",
      price: "510.000",
      image: "/images/Ao-Smaker18.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "85",
      rating5: "20",
      rating4: "30",
      rating3: "15",
      rating2: "10",
      rating1: "10",
    },
    {
      id: 18,
      tags: "Tshirts",
      name: "Zintai Tshirt",
      fit: "Oversized",
      price: "490.999",
      image: "/images/Ao-Smaker19.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "140",
      rating5: "30",
      rating4: "50",
      rating3: "40",
      rating2: "20",
      rating1: "0",
    },
    {
      id: 19,
      tags: "Tshirts",
      name: "Jinsink T-Shirt Smaker",
      fit: "Oversized",
      price: "399.000",
      image: "/images/Ao-Smaker20.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "170",
      rating5: "30",
      rating4: "50",
      rating3: "50",
      rating2: "30",
      rating1: "10",
    },
    {
      id: 20,
      tags: "Tshirts",
      name: "Bisnked T-Shirt Smaker",
      fit: "Oversized",
      price: "299.000",
      image: "/images/Ao-Smaker21.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "30",
      rating5: "30",
      rating4: "0",
      rating3: "0",
      rating2: "0",
      rating1: "0",
    },
    {
      id: 21,
      tags: "Tshirts",
      name: "Aidful Tshirt",
      fit: "Oversized",
      price: "489.000",
      image: "/images/Ao-Smaker22.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "82",
      rating5: "72",
      rating4: "5",
      rating3: "5",
      rating2: "0",
      rating1: "0",
    },
    {
      id: 22,
      tags: "Tshirts",
      name: "Litypris T-Shirt Smaker",
      fit: "Oversized",
      price: "479.000",
      image: "/images/Ao-Smaker23.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "67",
      rating5: "37",
      rating4: "10",
      rating3: "10",
      rating2: "0",
      rating1: "10",
    },
    {
      id: 23,
      tags: "Tshirts",
      name: "Tinity T-Shirt Smaker",
      fit: "Oversized",
      price: "289.000",
      image: "/images/Ao-Smaker24.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "141",
      rating5: "20",
      rating4: "50",
      rating3: "51",
      rating2: "10",
      rating1: "10",
    },
    {
      id: 24,
      tags: "Tshirts",
      name: "Zinsky Tshirt",
      fit: "Oversized",
      price: "255.000",
      image: "/images/Ao-Smaker25.jpg",
      materials:
        "Áo mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "10",
      rating5: "2",
      rating4: "0",
      rating3: "2",
      rating2: "2",
      rating1: "4",
    },

    // Shirts
    {
      id: 25,
      tags: "Shirts",
      name: "Quisma Shirts",
      fit: "Oversized",
      price: "599.000",
      image: "/images/Shirts-Smaker.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "10",
      rating5: "2",
      rating4: "0",
      rating3: "2",
      rating2: "2",
      rating1: "4",
    },
    {
      id: 26,
      tags: "Shirts",
      name: "Wispy Shirts",
      fit: "Oversized",
      price: "382.000",
      image: "/images/Shirts-Smaker2.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "310",
      rating5: "50",
      rating4: "100",
      rating3: "80",
      rating2: "70",
      rating1: "10",
    },
    {
      id: 27,
      tags: "Shirts",
      name: "Electric Shirts",
      fit: "Oversized",
      price: "387.000",
      image: "/images/Shirts-Smaker3.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "400",
      rating5: "50",
      rating4: "100",
      rating3: "100",
      rating2: "100",
      rating1: "50",
    },
    {
      id: 28,
      tags: "Shirts",
      name: "Risby Shirts",
      fit: "Oversized",
      price: "482.000",
      image: "/images/Shirt-Smaker4.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "50",
      rating5: "10",
      rating4: "20",
      rating3: "10",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 29,
      tags: "Shirts",
      name: "Yatai Shirts",
      fit: "Oversized",
      price: "365.000",
      image: "/images/Shirts-Smaker5.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "60",
      rating5: "20",
      rating4: "10",
      rating3: "12",
      rating2: "10",
      rating1: "10",
    },
    {
      id: 30,
      tags: "Shirts",
      name: "Unity Shirts",
      fit: "Oversized",
      price: "654.000",
      image: "/images/Shirts-Smaker6.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "150",
      rating5: "20",
      rating4: "50",
      rating3: "20",
      rating2: "40",
      rating1: "20",
    },
    {
      id: 31,
      tags: "Shirts",
      name: "Illness Shirts",
      fit: "Oversized",
      price: "567.000",
      image: "/images/Shirts-Smaker7.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "40",
      rating5: "10",
      rating4: "20",
      rating3: "0",
      rating2: "0",
      rating1: "10",
    },
    {
      id: 32,
      tags: "Shirts",
      name: "Prislity Shirts",
      fit: "Oversized",
      price: "543.000",
      image: "/images/Shirts-Smaker8.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "220",
      rating5: "220",
      rating4: "0",
      rating3: "0",
      rating2: "0",
      rating1: "0",
    },
    {
      id: 33,
      tags: "Shirts",
      name: "Daily Shirts",
      fit: "Oversized",
      price: "642.000",
      image: "/images/Shirts-Smaker9.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "440",
      rating5: "400",
      rating4: "10",
      rating3: "10",
      rating2: "10",
      rating1: "10",
    },
    {
      id: 34,
      tags: "Shirts",
      name: "Doughla Shirts",
      fit: "Oversized",
      price: "527.000",
      image: "/images/Shirts-Smaker10.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "390",
      rating5: "370",
      rating4: "5",
      rating3: "5",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 35,
      tags: "Shirts",
      name: "Jinkshi Shirts",
      fit: "Oversized",
      price: "721.000",
      image: "/images/Shirts-Smaker11.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "420",
      rating5: "220",
      rating4: "20",
      rating3: "60",
      rating2: "50",
      rating1: "70",
    },
    {
      id: 36,
      tags: "Shirts",
      name: "Nicetry Shirts",
      fit: "Oversized",
      price: "612.000",
      image: "/images/Shirts-Smaker12.jpg",
      materials:
        "Shirt + Outwears mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "420",
      rating5: "220",
      rating4: "20",
      rating3: "60",
      rating2: "50",
      rating1: "70",
    },

    // PANTS
    {
      id: 37,
      tags: "Pants",
      name: "Trouser Pants",
      fit: "Oversized",
      price: "740.000",
      image: "/images/Pants-Smaker.jpg",
      materials:
        "Quần mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.9",
      totalRating: "36",
      rating5: "30",
      rating4: "2",
      rating3: "2",
      rating2: "2",
      rating1: "0",
    },
    {
      id: 38,
      tags: "Pants",
      name: "Pleasure Pants",
      fit: "Oversized",
      price: "730.000",
      image: "/images/Pants-Smaker2.jpg",
      materials:
        "Quần mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.2",
      totalRating: "120",
      rating5: "60",
      rating4: "30",
      rating3: "10",
      rating2: "10",
      rating1: "10",
    },
    {
      id: 39,
      tags: "Pants",
      name: "Tracked Pants",
      fit: "Oversized",
      price: "650.000",
      image: "/images/Pants-Smaker3.jpg",
      materials:
        "Quần mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.6",
      totalRating: "60",
      rating5: "30",
      rating4: "10",
      rating3: "10",
      rating2: "10",
      rating1: "10",
    },
    {
      id: 40,
      tags: "Pants",
      name: "Cargo Pants",
      fit: "Oversized",
      price: "670.000",
      image: "/images/Pants-Smake4.jpg",
      materials:
        "Quần mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.6",
      totalRating: "70",
      rating5: "30",
      rating4: "20",
      rating3: "10",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 41,
      tags: "Pants",
      name: "Cardigan Pants",
      fit: "Oversized",
      price: "660.000",
      image: "/images/Pants-Smaker5.jpg",
      materials:
        "Quần mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.9",
      totalRating: "100",
      rating5: "80",
      rating4: "5",
      rating3: "5",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 42,
      tags: "Pants",
      name: "Plisma Pants",
      fit: "Oversized",
      price: "720.000",
      image: "/images/Pants-Smaker6.jpg",
      materials:
        "Quần mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.8",
      totalRating: "50",
      rating5: "30",
      rating4: "5",
      rating3: "5",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 43,
      tags: "Pants",
      name: "Sweide Pants",
      fit: "Oversized",
      price: "850.000",
      image: "/images/Pants-Smaker7.jpg",
      materials:
        "Quần mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.9",
      totalRating: "30",
      rating5: "30",
      rating4: "0",
      rating3: "0",
      rating2: "0",
      rating1: "0",
    },
    {
      id: 44,
      tags: "Pants",
      name: "Sweat Pants",
      fit: "Oversized",
      price: "812.000",
      image: "/images/Pants-Smaker8.jpg",
      materials:
        "Quần mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.9",
      totalRating: "200",
      rating5: "180",
      rating4: "5",
      rating3: "5",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 45,
      tags: "Pants",
      name: "Long Pants",
      fit: "Oversized",
      price: "713.000",
      image: "/images/Pants-Smaker10.jpg",
      materials:
        "Quần mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "4.9",
      totalRating: "150",
      rating5: "130",
      rating4: "5",
      rating3: "5",
      rating2: "5",
      rating1: "5",
    },
    {
      id: 46,
      tags: "Pants",
      name: "Suide Pants",
      fit: "Oversized",
      price: "738.000",
      image: "/images/Pants-Smaker11.jpg",
      materials:
        "Quần mang thương hiệu $maker được xuất sứ từ chất liệu cao cấp, mang lại cho người sử dụng cảm giác thoải mái và dễ chịu khi hoạt động. Được thiết kế độc đáo mang phong cách street-wear",
      rating: "1.3",
      totalRating: "13",
      rating5: "2",
      rating4: "2",
      rating3: "2",
      rating2: "2",
      rating1: "5",
    },
  ];

  return NextResponse.json(allCollections);
};
